# Generated by Django 2.2.6 on 2019-10-10 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creatder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='creatder.User'),
        ),
    ]
