# Generated by Django 2.2.6 on 2019-10-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatder', '0005_createaccounttoken_passwordresettoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
