# Generated by Django 2.2.6 on 2019-11-04 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creatder', '0007_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='creature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creatder.Creature'),
            preserve_default=False,
        ),
    ]
