# Generated by Django 2.2.6 on 2019-11-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatder', '0008_file_creature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='breed',
            field=models.CharField(choices=[('Other', 'Other'), ('American', 'American'), ('Abyssinian', 'Abyssinian'), ('Hairless', 'Hairless'), ('Himalayan', 'Himalayan'), ('Peruvian', 'Peruvian'), ('Rex', 'Rex'), ('Silkie', 'Silkie'), ('Teddy', 'Teddy'), ('White-crested', 'White-crested')], default='Other', max_length=15),
        ),
        migrations.AlterField(
            model_name='creature',
            name='color_pattern',
            field=models.CharField(choices=[('Self-Black', 'Self-Black'), ('Self-White', 'Self-White'), ('Self-Red', 'Self-Red'), ('Self-Cream', 'Self-Cream'), ('Agouti-Chocolate', 'Agouti-Chocolate'), ('Agouti-Golde', 'Agouti-Golde'), ('Agouti-Silver', 'Agouti-Silver'), ('Agouti-Cream', 'Agouti-Cream'), ('White-Black', 'White-Black'), ('White-Red', 'White-Red'), ('Red-Black', 'Red-Black'), ('White-Cream', 'White-Cream'), ('Brindle', 'Brindle'), ('Mix', 'Mix'), ('Albino', 'Albino')], default='Mix', max_length=20),
        ),
        migrations.AlterField(
            model_name='creature',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Not sure', 'Not sure')], default='Female', max_length=8),
        ),
    ]
