# Generated by Django 2.2.6 on 2019-11-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatder', '0009_auto_20191110_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creature',
            options={'ordering': ['-pub_date']},
        ),
    ]
