# Generated by Django 2.2.6 on 2019-12-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatder', '0010_auto_20191120_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
